/* @date 2023-06-29T13:07:22.915284822Z */

/**********************************************************************
 * @file rte_hook_cfg.h
 * 
 * Automatically generated by Software Producer Engineer
 * FMU middleware generator @version 100
 **********************************************************************/

/**********************************************************************
 * This file describes the task descriptor structure.
 * The task descriptor is a structure containing field specific to targets
 * and additional common members.
 * This file must exist and have this exact name
 **********************************************************************/

#ifndef RTE_HOOK_CFG_H
#define RTE_HOOK_CFG_H

#define RTE_ReadHook_Light_light_On
#define RTE_WriteHook_Light_light_On
#define RTE_ReadHook_Light_light_Off
#define RTE_WriteHook_Light_light_Off
#define RTE_ReadHook_Light_light_Tick
#define RTE_WriteHook_Light_light_Tick
#define RTE_ReadHook_Light_light_snd
#define RTE_WriteHook_Light_light_snd
#define RTE_ReadHook_Light_InputSignal_Tick
#define RTE_WriteHook_Light_InputSignal_Tick
#define RTE_ReadHook_Light_pout_io
#define RTE_WriteHook_Light_pout_io

#endif /* RTE_HOOK_CFG_H */

/* end of file */
