/* @date 2023-06-29T13:06:23.900186761Z */

/**********************************************************************
 * @file mw_hook.h
 *
 * Automatically generated by Software Producer Engineer
 * Runtime code generator @version 1.0.0
 **********************************************************************/

#ifndef MW_HOOK_H
#define MW_HOOK_H

#include "rte_hook_cfg.h"

#if defined(RTE_ReadHook_Timer_control_snd)
#undef ReadHook_Timer_control_snd
extern void RTE_ReadHook_Timer_control_snd_Start(Boolean* from_UNCONNECTED_control_snd);
extern void RTE_ReadHook_Timer_control_snd_Return(Boolean* from_UNCONNECTED_control_snd);
#else
#define RTE_ReadHook_Timer_control_snd_Start(value)  ((void) (0))
#define RTE_ReadHook_Timer_control_snd_Return(value)  ((void) (0))
#endif /* ReadHook_Timer_control_snd */

#if defined(RTE_ReadHook_Timer_control_On)
#undef ReadHook_Timer_control_On
extern void RTE_ReadHook_Timer_control_On_Start(SignalEvent_On_type* from_UNCONNECTED_control_On);
extern void RTE_ReadHook_Timer_control_On_Return(SignalEvent_On_type* from_UNCONNECTED_control_On);
#else
#define RTE_ReadHook_Timer_control_On_Start(value)  ((void) (0))
#define RTE_ReadHook_Timer_control_On_Return(value)  ((void) (0))
#endif /* ReadHook_Timer_control_On */

#if defined(RTE_ReadHook_Timer_control_Off)
#undef ReadHook_Timer_control_Off
extern void RTE_ReadHook_Timer_control_Off_Start(SignalEvent_Off_type* from_UNCONNECTED_control_Off);
extern void RTE_ReadHook_Timer_control_Off_Return(SignalEvent_Off_type* from_UNCONNECTED_control_Off);
#else
#define RTE_ReadHook_Timer_control_Off_Start(value)  ((void) (0))
#define RTE_ReadHook_Timer_control_Off_Return(value)  ((void) (0))
#endif /* ReadHook_Timer_control_Off */

#if defined(RTE_ReadHook_Timer_control_Tick)
#undef ReadHook_Timer_control_Tick
extern void RTE_ReadHook_Timer_control_Tick_Start(SignalEvent_Tick_type* from_UNCONNECTED_control_Tick);
extern void RTE_ReadHook_Timer_control_Tick_Return(SignalEvent_Tick_type* from_UNCONNECTED_control_Tick);
#else
#define RTE_ReadHook_Timer_control_Tick_Start(value)  ((void) (0))
#define RTE_ReadHook_Timer_control_Tick_Return(value)  ((void) (0))
#endif /* ReadHook_Timer_control_Tick */

#if defined(RTE_ReadHook_Timer_InputSignal_On)
#undef ReadHook_Timer_InputSignal_On
extern void RTE_ReadHook_Timer_InputSignal_On_Start(SignalEvent_On_type* from_UNCONNECTED_InputSignal_On);
extern void RTE_ReadHook_Timer_InputSignal_On_Return(SignalEvent_On_type* from_UNCONNECTED_InputSignal_On);
#else
#define RTE_ReadHook_Timer_InputSignal_On_Start(value)  ((void) (0))
#define RTE_ReadHook_Timer_InputSignal_On_Return(value)  ((void) (0))
#endif /* ReadHook_Timer_InputSignal_On */

#if defined(RTE_ReadHook_Timer_InputSignal_Off)
#undef ReadHook_Timer_InputSignal_Off
extern void RTE_ReadHook_Timer_InputSignal_Off_Start(SignalEvent_Off_type* from_UNCONNECTED_InputSignal_Off);
extern void RTE_ReadHook_Timer_InputSignal_Off_Return(SignalEvent_Off_type* from_UNCONNECTED_InputSignal_Off);
#else
#define RTE_ReadHook_Timer_InputSignal_Off_Start(value)  ((void) (0))
#define RTE_ReadHook_Timer_InputSignal_Off_Return(value)  ((void) (0))
#endif /* ReadHook_Timer_InputSignal_Off */


#if defined(RTE_WriteHook_Timer_light_snd)
#undef WriteHook_Timer_light_snd
extern void RTE_WriteHook_Timer_light_snd_Start(Boolean* from_UNCONNECTED_light_snd);
extern void RTE_WriteHook_Timer_light_snd_Return(Boolean* from_UNCONNECTED_light_snd);
#else
#define RTE_WriteHook_Timer_light_snd_Start(value)  ((void) (0))
#define RTE_WriteHook_Timer_light_snd_Return(value)  ((void) (0))
#endif /* WriteHook_Timer_light_snd */

#if defined(RTE_TriggerHook_Timer_light_On)
#undef TriggerHook_Timer_light_On
extern void RTE_TriggerHook_Timer_light_On_Start(SignalEvent_On_type* from_UNCONNECTED_light_On);
extern void RTE_TriggerHook_Timer_light_On_Return(SignalEvent_On_type* from_UNCONNECTED_light_On);
#else
#define RTE_TriggerHook_Timer_light_On_Start(value)  ((void) (0))
#define RTE_TriggerHook_Timer_light_On_Return(value)  ((void) (0))
#endif /* TriggerHook_Timer_light_On */

#if defined(RTE_TriggerHook_Timer_light_Off)
#undef TriggerHook_Timer_light_Off
extern void RTE_TriggerHook_Timer_light_Off_Start(SignalEvent_Off_type* from_UNCONNECTED_light_Off);
extern void RTE_TriggerHook_Timer_light_Off_Return(SignalEvent_Off_type* from_UNCONNECTED_light_Off);
#else
#define RTE_TriggerHook_Timer_light_Off_Start(value)  ((void) (0))
#define RTE_TriggerHook_Timer_light_Off_Return(value)  ((void) (0))
#endif /* TriggerHook_Timer_light_Off */

#if defined(RTE_TriggerHook_Timer_light_Tick)
#undef TriggerHook_Timer_light_Tick
extern void RTE_TriggerHook_Timer_light_Tick_Start(SignalEvent_Tick_type* from_UNCONNECTED_light_Tick);
extern void RTE_TriggerHook_Timer_light_Tick_Return(SignalEvent_Tick_type* from_UNCONNECTED_light_Tick);
#else
#define RTE_TriggerHook_Timer_light_Tick_Start(value)  ((void) (0))
#define RTE_TriggerHook_Timer_light_Tick_Return(value)  ((void) (0))
#endif /* TriggerHook_Timer_light_Tick */

#endif /* MW_HOOK_H */

/* end of file */
