/* @date 2023-06-29T13:05:39.828185796Z */

/**********************************************************************
 * @file mw_hook.h
 *
 * Automatically generated by Software Producer Engineer
 * Runtime code generator @version 1.0.0
 **********************************************************************/

#ifndef MW_HOOK_H
#define MW_HOOK_H

#include "rte_hook_cfg.h"

#if defined(RTE_ReadHook_Button_pin_io)
#undef ReadHook_Button_pin_io
extern void RTE_ReadHook_Button_pin_io_Start(Boolean* from_UNCONNECTED_pin_io);
extern void RTE_ReadHook_Button_pin_io_Return(Boolean* from_UNCONNECTED_pin_io);
#else
#define RTE_ReadHook_Button_pin_io_Start(value)  ((void) (0))
#define RTE_ReadHook_Button_pin_io_Return(value)  ((void) (0))
#endif /* ReadHook_Button_pin_io */


#if defined(RTE_WriteHook_Button_control_snd)
#undef WriteHook_Button_control_snd
extern void RTE_WriteHook_Button_control_snd_Start(Boolean* from_UNCONNECTED_control_snd);
extern void RTE_WriteHook_Button_control_snd_Return(Boolean* from_UNCONNECTED_control_snd);
#else
#define RTE_WriteHook_Button_control_snd_Start(value)  ((void) (0))
#define RTE_WriteHook_Button_control_snd_Return(value)  ((void) (0))
#endif /* WriteHook_Button_control_snd */

#if defined(RTE_TriggerHook_Button_control_On)
#undef TriggerHook_Button_control_On
extern void RTE_TriggerHook_Button_control_On_Start(SignalEvent_On_type* from_UNCONNECTED_control_On);
extern void RTE_TriggerHook_Button_control_On_Return(SignalEvent_On_type* from_UNCONNECTED_control_On);
#else
#define RTE_TriggerHook_Button_control_On_Start(value)  ((void) (0))
#define RTE_TriggerHook_Button_control_On_Return(value)  ((void) (0))
#endif /* TriggerHook_Button_control_On */

#if defined(RTE_TriggerHook_Button_control_Off)
#undef TriggerHook_Button_control_Off
extern void RTE_TriggerHook_Button_control_Off_Start(SignalEvent_Off_type* from_UNCONNECTED_control_Off);
extern void RTE_TriggerHook_Button_control_Off_Return(SignalEvent_Off_type* from_UNCONNECTED_control_Off);
#else
#define RTE_TriggerHook_Button_control_Off_Start(value)  ((void) (0))
#define RTE_TriggerHook_Button_control_Off_Return(value)  ((void) (0))
#endif /* TriggerHook_Button_control_Off */

#if defined(RTE_TriggerHook_Button_control_Tick)
#undef TriggerHook_Button_control_Tick
extern void RTE_TriggerHook_Button_control_Tick_Start(SignalEvent_Tick_type* from_UNCONNECTED_control_Tick);
extern void RTE_TriggerHook_Button_control_Tick_Return(SignalEvent_Tick_type* from_UNCONNECTED_control_Tick);
#else
#define RTE_TriggerHook_Button_control_Tick_Start(value)  ((void) (0))
#define RTE_TriggerHook_Button_control_Tick_Return(value)  ((void) (0))
#endif /* TriggerHook_Button_control_Tick */

#endif /* MW_HOOK_H */

/* end of file */
