/* @date 2023-06-29T13:05:39.828163505Z */

/**********************************************************************
 * @file mw.c
 *
 * Automatically generated by Software Producer Engineer
 * Runtime code generator @version 1.0.0
 **********************************************************************/

#include "mw_cfg.h"
#include "mw_hook.h"

#define RTE_C /* Macro to include only some specific parts of include files */
#include "Button_itf.h"

#ifdef RTE_DEBUG
#include <stdio.h>
#define debug(...) printf(__VA_ARGS__); fflush(stdout)
#else
#define debug(...)
#endif


task_descriptor task_descriptors[NUMBER_OF_TASKS];


/*
 * Rte instances declaration
 */
Rte_Button_Struct Button_inst;

/*
 * Shared variables definitions
 */
Boolean from_UNCONNECTED_control_snd;
SignalEvent_On_type from_UNCONNECTED_control_On;
SignalEvent_Off_type from_UNCONNECTED_control_Off;
SignalEvent_Tick_type from_UNCONNECTED_control_Tick;
Boolean from_UNCONNECTED_pin_io;

/*
 * Triggering functions
 */
void RTE_Trigger_Button_control_On(void){

	RTE_TriggerHook_Button_control_On_Start(&from_UNCONNECTED_control_On);
	debug("DEBUG: RTE_Trigger_Button_control_On: Enter\\\n");
	unsigned int byteIdx;
	from_UNCONNECTED_control_On.trigger = 1;
	debug("DEBUG: RTE_Write_Button_control_On: Exit\\\n");
	RTE_TriggerHook_Button_control_On_Return(&from_UNCONNECTED_control_On);
}

void RTE_Trigger_Button_control_Off(void){

	RTE_TriggerHook_Button_control_Off_Start(&from_UNCONNECTED_control_Off);
	debug("DEBUG: RTE_Trigger_Button_control_Off: Enter\\\n");
	unsigned int byteIdx;
	from_UNCONNECTED_control_Off.trigger = 1;
	debug("DEBUG: RTE_Write_Button_control_Off: Exit\\\n");
	RTE_TriggerHook_Button_control_Off_Return(&from_UNCONNECTED_control_Off);
}

void RTE_Trigger_Button_control_Tick(void){

	RTE_TriggerHook_Button_control_Tick_Start(&from_UNCONNECTED_control_Tick);
	debug("DEBUG: RTE_Trigger_Button_control_Tick: Enter\\\n");
	unsigned int byteIdx;
	from_UNCONNECTED_control_Tick.trigger = 1;
	debug("DEBUG: RTE_Write_Button_control_Tick: Exit\\\n");
	RTE_TriggerHook_Button_control_Tick_Return(&from_UNCONNECTED_control_Tick);
}


/*
 * Send functions
 */
void RTE_Write_Button_control_snd(Boolean* data){
	// Copy byte by byte
	unsigned int byteIdx;

	RTE_WriteHook_Button_control_snd_Start(&from_UNCONNECTED_control_snd);
	debug("DEBUG: RTE_Write_Button_control_snd: Enter\\\n");

	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) &from_UNCONNECTED_control_snd)[byteIdx] = ((char*) data)[byteIdx];
	}

	debug("DEBUG: RTE_Write_Button_control_snd: Exit\\\n");
	RTE_WriteHook_Button_control_snd_Return(&from_UNCONNECTED_control_snd);
}


/*
 * Read functions
 */
void RTE_Read_Button_pin_io(Boolean* data){
	unsigned int byteIdx;

	RTE_ReadHook_Button_pin_io_Start(&from_UNCONNECTED_pin_io);
	RTE_ReadHook_Button_pin_io_Return(&from_UNCONNECTED_pin_io);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_UNCONNECTED_pin_io)[byteIdx];
	}
}


/*
 * Server call functions
 */

double RTE_GetTime(void);

/*
 * Map the communication APIs to component instances
 */
void component_instances_init(void){
  /* BEG: Button Rte Instance configuration */
  /* Write functions */
  Button_inst.Write_control_snd = &RTE_Write_Button_control_snd;
  /* Trigger functions */
  Button_inst.Trigger_control_On = &RTE_Trigger_Button_control_On;
  Button_inst.Trigger_control_Off = &RTE_Trigger_Button_control_Off;
  Button_inst.Trigger_control_Tick = &RTE_Trigger_Button_control_Tick;
  /* Read functions */
  Button_inst.Read_pin_io = &RTE_Read_Button_pin_io;
  /* Server call functions */
  Button_inst.GetTime = &RTE_GetTime;
  /* END: Button Rte Instance configuration */

}

/*
 * Tasks initialization
 *
 * A56 - 12/6/2019: Initialization of global variables is done at runtime
 * because for some boards or compiling option static initialization fails
 * True for RIOT but code below could be done at variable declaration for Adaptive
 */
void task_descriptors_init(void){


}

void components_init(void) {
	Button_Button_init(&Button_inst);
}

/* end of file */
