/* @date 2023-06-29T13:07:22.932436120Z */

/**********************************************************************
 * @file mw.c
 *
 * Automatically generated by Software Producer Engineer
 * Runtime code generator @version 1.0.0
 **********************************************************************/

#include "mw_cfg.h"
#include "mw_hook.h"

#define RTE_C /* Macro to include only some specific parts of include files */
#include "Light_itf.h"

#ifdef RTE_DEBUG
#include <stdio.h>
#define debug(...) printf(__VA_ARGS__); fflush(stdout)
#else
#define debug(...)
#endif


task_descriptor task_descriptors[NUMBER_OF_TASKS];


/*
 * Rte instances declaration
 */
Rte_Light_Struct Light_inst;

/*
 * Shared variables definitions
 */
Boolean from_UNCONNECTED_pout_io;
Boolean from_UNCONNECTED_light_snd;
SignalEvent_On_type from_UNCONNECTED_light_On;
SignalEvent_Off_type from_UNCONNECTED_light_Off;
SignalEvent_Tick_type from_UNCONNECTED_light_Tick;
SignalEvent_Tick_type from_UNCONNECTED_InputSignal_Tick;

/*
 * Triggering functions
 */

/*
 * Send functions
 */
void RTE_Write_Light_pout_io(Boolean* data){
	// Copy byte by byte
	unsigned int byteIdx;

	RTE_WriteHook_Light_pout_io_Start(&from_UNCONNECTED_pout_io);
	debug("DEBUG: RTE_Write_Light_pout_io: Enter\\\n");

	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) &from_UNCONNECTED_pout_io)[byteIdx] = ((char*) data)[byteIdx];
	}

	debug("DEBUG: RTE_Write_Light_pout_io: Exit\\\n");
	RTE_WriteHook_Light_pout_io_Return(&from_UNCONNECTED_pout_io);
}


/*
 * Read functions
 */
void RTE_Read_Light_light_snd(Boolean* data){
	unsigned int byteIdx;

	RTE_ReadHook_Light_light_snd_Start(&from_UNCONNECTED_light_snd);
	RTE_ReadHook_Light_light_snd_Return(&from_UNCONNECTED_light_snd);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_UNCONNECTED_light_snd)[byteIdx];
	}
}

void RTE_Read_Light_light_On(SignalEvent_On_type* data){
	unsigned int byteIdx;

	RTE_ReadHook_Light_light_On_Start(&from_UNCONNECTED_light_On);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_On_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_UNCONNECTED_light_On)[byteIdx];
	}
	from_UNCONNECTED_light_On.trigger = 0;
	RTE_ReadHook_Light_light_On_Return(&from_UNCONNECTED_light_On);
}

void RTE_Read_Light_light_Off(SignalEvent_Off_type* data){
	unsigned int byteIdx;

	RTE_ReadHook_Light_light_Off_Start(&from_UNCONNECTED_light_Off);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Off_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_UNCONNECTED_light_Off)[byteIdx];
	}
	from_UNCONNECTED_light_Off.trigger = 0;
	RTE_ReadHook_Light_light_Off_Return(&from_UNCONNECTED_light_Off);
}

void RTE_Read_Light_light_Tick(SignalEvent_Tick_type* data){
	unsigned int byteIdx;

	RTE_ReadHook_Light_light_Tick_Start(&from_UNCONNECTED_light_Tick);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Tick_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_UNCONNECTED_light_Tick)[byteIdx];
	}
	from_UNCONNECTED_light_Tick.trigger = 0;
	RTE_ReadHook_Light_light_Tick_Return(&from_UNCONNECTED_light_Tick);
}

void RTE_Read_Light_InputSignal_Tick(SignalEvent_Tick_type* data){
	unsigned int byteIdx;

	RTE_ReadHook_Light_InputSignal_Tick_Start(&from_UNCONNECTED_InputSignal_Tick);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Tick_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_UNCONNECTED_InputSignal_Tick)[byteIdx];
	}
	from_UNCONNECTED_InputSignal_Tick.trigger = 0;
	RTE_ReadHook_Light_InputSignal_Tick_Return(&from_UNCONNECTED_InputSignal_Tick);
}


/*
 * Server call functions
 */

double RTE_GetTime(void);

/*
 * Map the communication APIs to component instances
 */
void component_instances_init(void){
  /* BEG: Light Rte Instance configuration */
  /* Write functions */
  Light_inst.Write_pout_io = &RTE_Write_Light_pout_io;
  /* Trigger functions */
  /* Read functions */
  Light_inst.Read_light_snd = &RTE_Read_Light_light_snd;
  Light_inst.Read_light_On = &RTE_Read_Light_light_On;
  Light_inst.Read_light_Off = &RTE_Read_Light_light_Off;
  Light_inst.Read_light_Tick = &RTE_Read_Light_light_Tick;
  Light_inst.Read_InputSignal_Tick = &RTE_Read_Light_InputSignal_Tick;
  /* Server call functions */
  Light_inst.GetTime = &RTE_GetTime;
  /* END: Light Rte Instance configuration */

}

/*
 * Tasks initialization
 *
 * A56 - 12/6/2019: Initialization of global variables is done at runtime
 * because for some boards or compiling option static initialization fails
 * True for RIOT but code below could be done at variable declaration for Adaptive
 */
void task_descriptors_init(void){


}

void components_init(void) {
	Light_Light_init(&Light_inst);
}

/* end of file */
