/* @date 2023-06-29T13:07:22.932457203Z */

/**********************************************************************
 * @file mw_hook.h
 *
 * Automatically generated by Software Producer Engineer
 * Runtime code generator @version 1.0.0
 **********************************************************************/

#ifndef MW_HOOK_H
#define MW_HOOK_H

#include "rte_hook_cfg.h"

#if defined(RTE_ReadHook_Light_light_snd)
#undef ReadHook_Light_light_snd
extern void RTE_ReadHook_Light_light_snd_Start(Boolean* from_UNCONNECTED_light_snd);
extern void RTE_ReadHook_Light_light_snd_Return(Boolean* from_UNCONNECTED_light_snd);
#else
#define RTE_ReadHook_Light_light_snd_Start(value)  ((void) (0))
#define RTE_ReadHook_Light_light_snd_Return(value)  ((void) (0))
#endif /* ReadHook_Light_light_snd */

#if defined(RTE_ReadHook_Light_light_On)
#undef ReadHook_Light_light_On
extern void RTE_ReadHook_Light_light_On_Start(SignalEvent_On_type* from_UNCONNECTED_light_On);
extern void RTE_ReadHook_Light_light_On_Return(SignalEvent_On_type* from_UNCONNECTED_light_On);
#else
#define RTE_ReadHook_Light_light_On_Start(value)  ((void) (0))
#define RTE_ReadHook_Light_light_On_Return(value)  ((void) (0))
#endif /* ReadHook_Light_light_On */

#if defined(RTE_ReadHook_Light_light_Off)
#undef ReadHook_Light_light_Off
extern void RTE_ReadHook_Light_light_Off_Start(SignalEvent_Off_type* from_UNCONNECTED_light_Off);
extern void RTE_ReadHook_Light_light_Off_Return(SignalEvent_Off_type* from_UNCONNECTED_light_Off);
#else
#define RTE_ReadHook_Light_light_Off_Start(value)  ((void) (0))
#define RTE_ReadHook_Light_light_Off_Return(value)  ((void) (0))
#endif /* ReadHook_Light_light_Off */

#if defined(RTE_ReadHook_Light_light_Tick)
#undef ReadHook_Light_light_Tick
extern void RTE_ReadHook_Light_light_Tick_Start(SignalEvent_Tick_type* from_UNCONNECTED_light_Tick);
extern void RTE_ReadHook_Light_light_Tick_Return(SignalEvent_Tick_type* from_UNCONNECTED_light_Tick);
#else
#define RTE_ReadHook_Light_light_Tick_Start(value)  ((void) (0))
#define RTE_ReadHook_Light_light_Tick_Return(value)  ((void) (0))
#endif /* ReadHook_Light_light_Tick */

#if defined(RTE_ReadHook_Light_InputSignal_Tick)
#undef ReadHook_Light_InputSignal_Tick
extern void RTE_ReadHook_Light_InputSignal_Tick_Start(SignalEvent_Tick_type* from_UNCONNECTED_InputSignal_Tick);
extern void RTE_ReadHook_Light_InputSignal_Tick_Return(SignalEvent_Tick_type* from_UNCONNECTED_InputSignal_Tick);
#else
#define RTE_ReadHook_Light_InputSignal_Tick_Start(value)  ((void) (0))
#define RTE_ReadHook_Light_InputSignal_Tick_Return(value)  ((void) (0))
#endif /* ReadHook_Light_InputSignal_Tick */


#if defined(RTE_WriteHook_Light_pout_io)
#undef WriteHook_Light_pout_io
extern void RTE_WriteHook_Light_pout_io_Start(Boolean* from_UNCONNECTED_pout_io);
extern void RTE_WriteHook_Light_pout_io_Return(Boolean* from_UNCONNECTED_pout_io);
#else
#define RTE_WriteHook_Light_pout_io_Start(value)  ((void) (0))
#define RTE_WriteHook_Light_pout_io_Return(value)  ((void) (0))
#endif /* WriteHook_Light_pout_io */

#endif /* MW_HOOK_H */

/* end of file */
