/* @date 2023-06-29T13:05:39.813159274Z */

/**********************************************************************
 * @file rte_hook_cfg.h
 * 
 * Automatically generated by Software Producer Engineer
 * FMU middleware generator @version 100
 **********************************************************************/

/**********************************************************************
 * This file describes the task descriptor structure.
 * The task descriptor is a structure containing field specific to targets
 * and additional common members.
 * This file must exist and have this exact name
 **********************************************************************/

#ifndef RTE_HOOK_CFG_H
#define RTE_HOOK_CFG_H

#define RTE_ReadHook_Button_pin_io
#define RTE_WriteHook_Button_pin_io
#define RTE_ReadHook_Button_control_On
#define RTE_TriggerHook_Button_control_On
#define RTE_ReadHook_Button_control_Off
#define RTE_TriggerHook_Button_control_Off
#define RTE_ReadHook_Button_control_Tick
#define RTE_TriggerHook_Button_control_Tick
#define RTE_ReadHook_Button_control_snd
#define RTE_WriteHook_Button_control_snd

#endif /* RTE_HOOK_CFG_H */

/* end of file */
